### ISSUE TITLE
not refreshing !

### ISSUE THREAD

**Issue by acathon** [jgulick48/NiceHashProfitabilityCalculator#1]
Nothing is changed !
I'm  running it since when its downloaded ! and all what I see is some "double" numbers
![image](https://user-images.githubusercontent.com/8994370/34624499-d0c46ea2-f255-11e7-82f4-332662ee9eb1.png)

**Comment by meskone1224** [comment]
@Acathon  I've downloaded and its working fine for me. Try changing refresh time to 30 seconds. That worked for me.

**Comment by acathon** [comment]
I've tried that too .. and all what I got is the same shown result ..

**Comment by jgulick48** [comment]
Let me take a look. I have everything suppressing errors currently.

**Comment by jgulick48** [comment]
@Acathon can you try running this debug release and send me a screen shot of any popups https://github.com/jgulick48/NiceHashProfitabilityCalculator/releases/tag/1.0.0.1

**Comment by acathon** [comment]
So I got this message with your new pre released version
![image](https://user-images.githubusercontent.com/8994370/34629055-0cbdbeca-f267-11e7-875a-f710c3fa77b4.png)

**Comment by jgulick48** [comment]
@Acathon added another debug release here to see what is going on.  I'm not getting the same errors when run on my system but this should give me more information.

https://github.com/jgulick48/NiceHashProfitabilityCalculator/releases/tag/1.0.0.2

**Comment by acathon** [comment]
![image](https://user-images.githubusercontent.com/8994370/34629687-5cade58e-f269-11e7-8b58-3b2455520365.png)

**Comment by jgulick48** [comment]
This one should work for you now.

https://github.com/jgulick48/NiceHashProfitabilityCalculator/releases/tag/1.0.0.3

**Comment by acathon** [comment]
nah it's the same.. nothing is changed ! 
![image](https://user-images.githubusercontent.com/8994370/34630019-a2f76d3e-f26a-11e7-985c-81c100a81e74.png)

**Comment by jgulick48** [comment]
I fixed the tryparse but not the actual parsing.  Now it should work.
https://github.com/jgulick48/NiceHashProfitabilityCalculator/releases/tag/1.0.0.4

**Comment by acathon** [comment]
another problem has been catched ..
![image](https://user-images.githubusercontent.com/8994370/34630325-e84488a8-f26b-11e7-94b1-4010a079daf5.png)

**Comment by jgulick48** [comment]
This has been quite the learning experience.  First time working with non en-US OS's.

https://github.com/jgulick48/NiceHashProfitabilityCalculator/releases/tag/1.0.0.5

Try that one.

**Comment by acathon** [comment]
could you push executable  app

**Comment by jgulick48** [comment]
Forgot to add the zip.  Added

**Comment by acathon** [comment]
We've got another thing here ..  
![image](https://user-images.githubusercontent.com/8994370/34630827-064eaa02-f26e-11e7-8af1-28e7c81a584a.png)

**Comment by jgulick48** [comment]
Good news is now its able to actually get the data from the API.  Just the display isn't working properly.

**Comment by jgulick48** [comment]
Here's another one
https://github.com/jgulick48/NiceHashProfitabilityCalculator/releases/tag/1.0.0.6

**Comment by acathon** [comment]
it remains the same issue ...  did you use Decimal.parse?

**Comment by jgulick48** [comment]
Yeah, there were some parsing from the db retrieval that probably did it.

https://github.com/jgulick48/NiceHashProfitabilityCalculator/releases/tag/1.0.0.7

**Comment by acathon** [comment]
NaN that's what seeing .. nothing is changed from your last build
![image](https://user-images.githubusercontent.com/8994370/34634320-2377c0fe-f283-11e7-8777-9de95f47fb5c.png)

**Comment by jgulick48** [comment]
This has been resolved with the 1.0.0.67 release.
