### ISSUE TITLE
Error in SQL Syntax

### ISSUE THREAD

**Issue by rgjertsen** [jgulick48/NiceHashProfitabilityCalculator#2]
Hi,
I tried using this StatsViewer but I can't get it to work.
I got the Monitor to start. I got a few errors here too, but it worked eventually.
When I try to start the StatViewer, I am getting an error I don't understand.
![nivehashstatviewer error](https://user-images.githubusercontent.com/35190050/34648585-09d7bc02-f39c-11e7-8d49-e1628f425371.jpg)
Some of the text are in norwegian..
Is this because the monitor haven't run for long enough?
I have tried it both on the mining computer, and on an external computer.

**Comment by rgjertsen** [comment]
I actually got it to work now. So I guess the start time HAVE to be after the Monitor was started?

**Comment by rgjertsen** [comment]
I also see that the Rig Stats shows estimated daily earnings of about 0,00014 BTC and the Card Stats shows 0,0008 BTC for my 960. How come the card stats shows more then the rig stats?

**Comment by rgjertsen** [comment]
I have set it to "Live" and every minute it should update, I get one of these errors and the graph doesn't update,
![nivehashstatviewer error 2](https://user-images.githubusercontent.com/35190050/34648718-834d31ae-f39f-11e7-9c66-0e5b9ec8890d.jpg)

**Comment by jgulick48** [comment]
Try this one
https://github.com/jgulick48/NiceHashProfitabilityCalculator/releases/tag/1.0.0.11

**Comment by rgjertsen** [comment]
Getting A LOT of the same errors. Every time it should update in live, and every time I enter a new time for "End Time". I also get a problem when I enter a P.M. time in "End", but it seems like A.M. works sort of..
I'm not an expert here, so this info may not help very much.. Some of it may even be wrong.

**Comment by jgulick48** [comment]
Chances are its due to the non english OS.  I'll see what I can do to prioritize an export to CSV and make some Shell Excel files people can use to make some graphs out side of the app while I work on the OS support.  I'm also going to add some more error logging so I can get some more details as to what is causing the crashes.

**Comment by rgjertsen** [comment]
Ok man, thanks :) Really like the consept though! I really would like the opportunity to see how much each card is making :) This way I could tell when each card has payed for itself :)

**Comment by jgulick48** [comment]
Keep the monitor running and I can hopefully get some reports working for you.

**Comment by rgjertsen** [comment]
No problem.

**Comment by jgulick48** [comment]
The issue with the 960 showing the improper earnings should be fixed now.

**Comment by jgulick48** [comment]
@rgjertsen I just created a new release for you to run for a bit that logs error messages to the database for review.  It should give you and error ID to report back with so I can take a look.

https://github.com/jgulick48/NiceHashProfitabilityCalculator/releases/tag/1.0.0.15

**Comment by rgjertsen** [comment]
Now I am only getting errors and no error ID.
The folder I extracted was actually called 1.0.0.14.
Could that be it?

**Comment by jgulick48** [comment]
Yeah, that release got buggered.  Have a new one

https://github.com/jgulick48/NiceHashProfitabilityCalculator/releases/tag/1.0.0.16

**Comment by rgjertsen** [comment]
Windows is stopping this as a virus..

**Comment by jgulick48** [comment]
That is smart screen due to it not being a signed app. Code validation certs are expensive but you should still be able to run it.

**Comment by rgjertsen** [comment]
I just opened the program, entered my BTC address and "Run Report". I did not change the times. Got an error number 4.
Do I have to enter times after I started the monitoring?

**Comment by rgjertsen** [comment]
Now I entered a start time I am pretty sure in after I started monitoring and got error number 5.

**Comment by rgjertsen** [comment]
Last time I entered just the last hour, and got error number 9.

**Comment by jgulick48** [comment]
Yeah looking at the errors I know what is going on. I’ll try to got it patched tomorrow night.

**Comment by jgulick48** [comment]
Try using this new release.  Hopefully the sql syntax isn't bonkers anymore.

https://github.com/jgulick48/NiceHashProfitabilityCalculator/releases/tag/1.0.0.17

**Comment by rgjertsen** [comment]
Do I have to download the new 17 for both the monitored pc an the one I use statviewer?

**Comment by rgjertsen** [comment]
And do I have to pick a Storage Type? If so, which?

**Comment by rgjertsen** [comment]
Some updates:
The program seems to work very well now! It logs without errors and updates in live also!
I also love the buttons for Last X hours!

A few bugs:
The "Use Friendly Name" check box doesn't move when I make the window bigger, so it's in the way for the text. The "Live" box moves fine.
The number for estimated earnings is HUUGE! It says I am making 23 with 13 zeros BTC per day. I would bet that is wrong.

Suggestions:
- I would love a "Live" box for the Card Stats page also.
- I would also like a textbox by the "Last X Hours" buttons where I can enter how many hours I would like it to display? Without changing the time itself.

**Comment by rgjertsen** [comment]
I see that all numbers are VEERY high. Watts, earnings, efficiency etc.

**Comment by jgulick48** [comment]
The release for 17 has both apps in it.  Right now you don't have to select a storage option as it only uses MySQL for the time being.

Added your suggestions in release:
https://github.com/jgulick48/NiceHashProfitabilityCalculator/releases/tag/1.0.0.18

Can you send me a screen shot of what the numbers look like?  Chances are its just a formatting issue due to the language.

**Comment by rgjertsen** [comment]
Did you add the folder there? Can't see the 18 folder in Assets.

**Comment by jgulick48** [comment]
There should be one now.

**Comment by rgjertsen** [comment]
![nh sw numbers](https://user-images.githubusercontent.com/35190050/34737299-11b7e592-f576-11e7-94bd-b4901c588bb9.png)

Here you can see the numbers are wrong.

**Comment by rgjertsen** [comment]
I have two more questions about some features.
1. I see the pictures of the first version of the monitor and I see the profit page. I would like to have a tab where I can see the profits of all my rigs and cards like the old version.
2. I am no programmer, so I don't know if this is possible at this time. But I was thinking about an opportunity to update the app without downloading a new version and deleting the old one all the time? Like just an update button of some sort? I'm not sure if even NH has this though..

**Comment by jgulick48** [comment]
1. The original stats viewer is based on the wallet address and pulls from NiceHash's API.  As I work towards supporting NHML I'll add the ability to make a "Master" node that does the logging for that information so that it isn't duplicated in the database.

2. That is one of the things I want to add in is a version check by the app that then gives you the option to have it launch a downloader to replace the files.  Shouldn't be too hard to implement but that will be a day or so out.  I'll see what I might be able to do with that soon though given the number of releases that are being pushed out.

I'm still working out what may be causing your balances display to be off that much.  They are logging properly in the database just fine its the viewer that is having the problem.  I'll see what I can do to fix it but since it only occurs on non english OS's its proving quite difficult to track down.

**Comment by rgjertsen** [comment]
Ok, looking forward to it!
Do you want me to run this for some logging? Or can I shut NH down for some alt coin mining until I hear from you again? It's not a problem if you want me to run NH for a few days though.

**Comment by jgulick48** [comment]
Up to you.  I have some data from you already on the logging front to test with and I think I found what was going wrong.  I'm going to try to get the updater completed tonight though since it shouldn't be that bad to do.

**Comment by rgjertsen** [comment]
Ok, I'll hear from you for #19 :)

**Comment by rgjertsen** [comment]
![image](https://user-images.githubusercontent.com/35190050/34775413-6714d796-f613-11e7-9723-bd8f7f6021ff.png)

Do you know why I get these dips? When you look at the gaming pc graph it also changes alot. Can this be algo changing? Or bugs? They are a little large for algo switching I think.

**Comment by jgulick48** [comment]
There have been some issues with one of the algos recently that may have caused the dips and spikes like that.  I'll do some further digging though.  I'm currently working on getting a CI pipeline set up so that builds are easier to push out and then I'll work on the auto updater but the next release should have the number format fixed.

**Comment by jgulick48** [comment]
v51 (big jump i know) has been published which should give you better numbers.  Next step is to work on the auto updater.

**Comment by rgjertsen** [comment]
I'm still getting the high numbers.
![image](https://user-images.githubusercontent.com/35190050/34783140-01f73666-f62b-11e7-81ec-cddf4213ae06.png)

**Comment by rgjertsen** [comment]
Maybe it should say what version I am using in the bottom left corner or something so that I'm sure :P 
Was a little bit different this time when there was a separate monitor folder with just the monitor in it.

**Comment by jgulick48** [comment]
What language OS are you using.  I'm going to set up a vm to do some debugging on that os version.

Also the latest release now has update notification and download option.  It now checks every hour and notifies you if there is an update via the bottom of the app.

**Comment by rgjertsen** [comment]
I am using a norwegian OS.
I’ll download the new version tomorrow. Would it be possible to add the software version in a corner as well? Nothing that needs it’s own update, but would be nice to have. QoL type of thing.


10. jan. 2018 kl. 23:14 skrev jgulick48 <notifications@github.com<mailto:notifications@github.com>>:


What language OS are you using. I'm going to set up a vm to do some debugging on that os version.

Also the latest release now has update notification and download option. It now checks every hour and notifies you if there is an update via the bottom of the app.

**Comment by rgjertsen** [comment]
A few updates:
I downloaded #62 and I get a notification even though I am on the last version.
This notification doesn't go away even though I press it and the downloader completes.
Also when I press patch  notes, nothing happens.

And if I have a PC where I only use the Viewer and not the Monitor, shouldn't there be a notification in the Viewer as well? Now I can only see one in the Monitor.

**Comment by rgjertsen** [comment]
I also see that the program is now detected by GeForce Experience and are given an overlay with FPS and some other stuff. Don't know if there is something to do with that.

**Comment by jgulick48** [comment]
Build 63 should fix the update system for the Monitor to have it properly check now.  That link will only show if the version running is older than the latest on github.  It now auto checks every hour to see if there is an update and then just displays the message.

**Comment by rgjertsen** [comment]
I downloaded the 63 version now, and it seems like it's working. I don't see any notifications.
Haven't tested the numbers though. I changed to alt coins for now.

**Comment by jgulick48** [comment]
If the viewer is left open you should see a notification within an hour.  You can use the viewer to see past data without needing to log more data for testing.  the 64 version should also fix the number displays.

**Comment by rgjertsen** [comment]
What about getting the notification in the Viewer as well, since I only use the viewer on the computer I use daily?

**Comment by rgjertsen** [comment]
And the numbers look like they work great now!

**Comment by jgulick48** [comment]
The Viewer will show the same type of notification when there is an update.  Since the numbers and errors have cleared up I'm going to close out this issue.  If you have any other problems or have new feature requests I'm tracking stuff on my JIRA instance at https://jira.threegm.com/projects/NPC/issues and will convert any issues here over there.

**Comment by rgjertsen** [comment]
Never used this site. It seemed a little more complicated than this.. :P 
How do I submit a new feature suggestion?

**Comment by jgulick48** [comment]
Go ahead and create them on github. And I’ll make a copy onto Jira for my work in progress stuff and then update the issues on github.

**Comment by rgjertsen** [comment]
Aha, ok. Thanks.
