### ISSUE TITLE
Unable to update from Viewer

### ISSUE THREAD

**Issue by rgjertsen** [jgulick48/NiceHashProfitabilityCalculator#25]
![image](https://user-images.githubusercontent.com/35190050/34843013-8ef1558c-f70d-11e7-98cc-1d6a877a567d.png)
As you can see the Viewer notifies me that there is a new update ready.
When I click the link, the Updater opens and the Viewer closes down. I just get an error message that it can't update because the Viewer is still running even it is closed.
![image](https://user-images.githubusercontent.com/35190050/34843083-c3e96b3a-f70d-11e7-8448-6ce902a483c6.png)

**Comment by jgulick48** [comment]
I'll add in small delay for the updater to start running.  If you run the Updater.exe by itself though it will update just fine.

**Comment by rgjertsen** [comment]
Yea, I noticed. Would be great with the delay, though :)

**Comment by jgulick48** [comment]
Fixed in sha f92f29e6d66a6a82bceba5289e85c85b664f1d41

**Comment by rgjertsen** [comment]
Great :) Waiting for the release.

**Comment by rgjertsen** [comment]
But in the Assets I see "Application", "Downloader" and "Tracker". Do I need to download them all? I didn't download the "downloader" folder last time since there is a folder called that in the "Application" folder already.

**Comment by jgulick48** [comment]
You just need the application.  The downloader is there for the update to auto download its installer.  Tracker is the initial little app that doesn't really do much.

**Comment by rgjertsen** [comment]
Would it be possible to make it so that I could only use one monitor window to monitor all my cards? Or a whole rig? As I have understood now I need one separate monitor running for each card?

**Comment by rgjertsen** [comment]
And another thing I think would be OK to have was that the last recorded number or value would show under the rig name or card name. So you could check the graph for historic numbers, but you could get the "current" rate on the sidebar under the corrosponding rig or card :)
And maybe an average over the last 3 or 12 hours? That may be a little more accurate than current value :)
Should I make a separate issue for all these feature suggestions? :P

**Comment by jgulick48** [comment]
You only need one instance of the monitor running per rig. The drop down for the cards is only so you can give them a friendly name and see their current stats but it logs data for all the cards. 

I’ll make a live dashboard that shows the stats for the last minute or so and auto refreshes.

**Comment by rgjertsen** [comment]
Ok :)
I was also wondering about the "wallet" info that you get if you log onto nicehash's site. Is it possible to get that with the API? Would be nice to chech your unpaid and paid balance in th wallet.
So it could be like a wallet tab in the viewer window?

**Comment by jgulick48** [comment]
Yeah the initial iteration only used the api. I’ll put that on the live dashboard.

**Comment by rgjertsen** [comment]
Ok. When do you expect to have this release out? Haven’t seen an update for some days.

**Comment by jgulick48** [comment]
I’m moving to a weekly release to prevent spamming the watchers on github. If I get a sizeable amount of work done early I’ll do a release.

**Comment by rgjertsen** [comment]
I have also noticed another thing. 
When I use the "Last 3 Hours" button, it's start time doesn't change ing "Live" mode.
Is it possible to get this to follow so that it only shows 3 hours all the time?
This way I would not have to generate the graph myself manually.

**Comment by jgulick48** [comment]
This should all be released with the latest 1.0.0.69 version which is out now.

**Comment by rgjertsen** [comment]
The bug is still there.
The text now says that it's waiting 5 seconds to run the updater, but the error that Viewer is still running is also there the same time.

**Comment by rgjertsen** [comment]
The Monitor also just shows NaN now. Has been that way for 30 minutes. Maybe it's because the rig is dual mining on NiceHash? One card is dual mining DaggerHashimoto and Decred, but both cards are showing NaN.

**Comment by rgjertsen** [comment]
I just saw in twitter that they have maintenance on some services from 10-12 CET, so this may be the reason? I'll see after this is done.

**Comment by jgulick48** [comment]
I'll change the logic on the updater to just try to delete files and if it finds one it can't throw an error instead.
