### ISSUE TITLE
Error when pressing the run report button (happens with both MySql and sqlite)

### ISSUE THREAD

**Issue by AtlAntA118** [jgulick48/NiceHashProfitabilityCalculator#3]
MySql.Data.MySqlClient.MySqlException (0x80004005): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '94987 and TimeRecorded <= 1515440305,92982 group by R.WorkerName, ROUND(cs.TimeR' at line 1
   bij MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   bij MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   bij MySql.Data.MySqlClient.Driver.GetResult(Int32 statementId, Int32& affectedRows, Int64& insertedId)
   bij MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   bij MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   bij MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   bij MySql.Data.MySqlClient.MySqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   bij System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   bij System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   bij System.Data.Common.DbDataAdapter.Fill(DataTable[] dataTables, Int32 startRecord, Int32 maxRecords, IDbCommand command, CommandBehavior behavior)
   bij System.Data.Common.DbDataAdapter.Fill(DataTable dataTable)
   bij NiceHashStatsViewer.DataHelper.MySQLHandler.GetDataTableFromSQL(String sql) in C:\Users\jeremy.gulick\Documents\NiceHashProfitabilityCalculator\NiceHash Profitability Tracker\NiceHashStatsViewer\DataHelper\MySQLHelper.cs:regel 20
   bij NiceHashStatsViewer.DataHelper.DataBaseHandler.GetDataTableFromSQL(String sql) in C:\Users\jeremy.gulick\Documents\NiceHashProfitabilityCalculator\NiceHash Profitability Tracker\NiceHashStatsViewer\DataHelper\DataBaseHelper.cs:regel 18
   bij NiceHashStatsViewer.Reports.RigReports.RunRigStatReport(String stat, String WalletAddress, DateTime start, DateTime end, Int32 resolution, Boolean sum) in C:\Users\jeremy.gulick\Documents\NiceHashProfitabilityCalculator\NiceHash Profitability Tracker\NiceHashStatsViewer\Reports\RigReports.cs:regel 57
   bij NiceHashStatsViewer.Reports.RigReports.RunRigStatAndGenerateChart(String WalletAddress, DateTime start, DateTime end, Int32 resolution, CartesianChart chart, String MetricColumn, String YKey, String LegendColumn, Boolean sum, String numberFormat) in C:\Users\jeremy.gulick\Documents\NiceHashProfitabilityCalculator\NiceHash Profitability Tracker\NiceHashStatsViewer\Reports\RigReports.cs:regel 20
   bij NiceHashStatsViewer.NicehashStatsViewer.RunRigStatReport(Int32 resolution) in C:\Users\jeremy.gulick\Documents\NiceHashProfitabilityCalculator\NiceHash Profitability Tracker\NiceHashStatsViewer\NicehashStatsViewer.cs:regel 53

**Comment by AtlAntA118** [comment]
I am by no means an expert but a lot of those paths seem to be looking for you as a user?

**Comment by jgulick48** [comment]
Those paths are from where it was complied.  I'm working on setting up a CI box to do the build and publish for me to make that easier.  As for the error, are you on an English OS?  It looks like the numbers are formatted a little weird.

**Comment by AtlAntA118** [comment]
No i'm on a dutch OS. Guess thats the problem then?
Maybe its because US uses the dates "wrong"? m/d/y instead of d/m/y?

**Comment by jgulick48** [comment]
Nah, the dates are formatted in unix time so there isn't any issue there.  The main issue is that the decimal places in numbers is coming through as a comma instead of a period which messes up SQL syntax.

Try this release as it should fix that.

https://github.com/jgulick48/NiceHashProfitabilityCalculator/releases/tag/1.0.0.17

**Comment by AtlAntA118** [comment]
Yes working fine now. Thanks!
