### ISSUE TITLE
[ER] Add electricity cost calculations

### ISSUE THREAD

**Issue by smoochy** [jgulick48/NiceHashProfitabilityCalculator#36]
In wide parts of the world electricity is not as cheap as in the US or even free.

For instance where I live I have to pay 0.02611 Euro cent per kWh.

Hence it is important for me to know, if it is more efficient to limit the GPU TDP to 65% and get a decrease in hashing power, or if it is better at 85% with increased power consumption (and electricity bill) and hash rate.

I thought of having the ability to enter the costs per kWh somewhere (or just set them in a config file for the beginning) and that the Live views of Rig Stats and of course the Exports contain calculations. In addition I need to be able to add the consumption of the rest of the mining rig (i.e. my computer has a power consumption of about 80W when running in idle modus. When I am mining with both cards and 65% TDP on each, the cards are having a consumption of 223W. But my computer in total has a consumption of 305W. Hence I need to take the 305W into calculation about efficiency.

In the live view I can see my estimated earnings and the power consumption of the cards. There it could be possible to add information about power consumption per day and costs per day.

**Comment by jgulick48** [comment]
I think the best way to handle this is going to be allowing the Monitor application to set a power cost and base power amount on each individual rig.  I can then update the live view to include the estimated power usage per day.  One other thing I'm looking at adding is a way to track/show a recent BTC/FIAT currency conversion so that you can see dollar amounts as well.  This may be a bit further in the future but I'll get the power cost and base power usage added to the Monitor app.

Converted to Jira so you can monitor progress at https://jira.threegm.com/browse/NPC-18

**Comment by smoochy** [comment]
I just found [an article](http://cryptomining-blog.com/8572-looking-for-the-efficiency-sweet-spot-of-gtx-1080-ti/), which is dealing with efficiency. An a measurement of hashes per Watt (H/W).

This being added would also be a huge benefit.

PS: Don't forget that there also other currencies than just Dollars :)


Thanks for your effort.

**Comment by jgulick48** [comment]
Yeah, this is where the raw exports will probably help in the short term.  I'm going to see if I can put together a few shells that you can drop data into for easy calculations.  I think I'm also going to add in logging to get the current TDP % on the cards to help out with this.

**Comment by jgulick48** [comment]
As for the conversions, I was looking at adding a currency table and then record the BTC conversion rates for various currencies and so you select your currency type on the monitor and it changes how it displays in the app.

**Comment by smoochy** [comment]
Yes, this would be helpful. Just don't forget that auto start thingy with the monitor :)

**Comment by jgulick48** [comment]
Yep, ticket already logged for that and that should be one of the first things done since its an easy to do thing.

**Comment by smoochy** [comment]
Sorry that came out wrong.

You said

> so you select your currency type on the monitor and it changes how it displays in the app.

I meant to say, that once I have set the currency I would like to use (for me it is EUR), that should be saved and that, when I later start the monitor again, it should not ask again, but directly start the monitor app (and start monitoring) like described in https://github.com/jgulick48/NiceHashProfitabilityCalculator/issues/35

**Comment by jgulick48** [comment]
Yep.

**Comment by jgulick48** [comment]
This change has been released with v1.0.0.74
