### ISSUE TITLE
[ER] App starts up again after update

### ISSUE THREAD

**Issue by rgjertsen** [jgulick48/NiceHashProfitabilityCalculator#39]
I think it would be great if the app started back up after you run the updater from the link in the monitor or viewer.
Maybe even add that the app updates automatically?

**Comment by jgulick48** [comment]
Added to the backlog and hopefully I can get a fix out for this tonight.

**Comment by jgulick48** [comment]
Fixed in [v1.0.0.76](https://github.com/jgulick48/NiceHashProfitabilityCalculator/releases/tag/1.0.0.76)
