### ISSUE TITLE
[Bug] Monitor App: Edit Rig not working

### ISSUE THREAD

**Issue by smoochy** [jgulick48/NiceHashProfitabilityCalculator#44]
The "Edit Rig" Button in the monitor app is not working. Clicking on it, does nothing.

Do I remember correctly that this button opened a little window, where wallet address and workername could be edited?

The reason for https://github.com/jgulick48/NiceHashProfitabilityCalculator/issues/43 is: Some days ago, I renamed the worker. And now in the Exports both workers (the old name of the worker and the new name) show up with the same data.

**Comment by jgulick48** [comment]
Added to the backlog for a bugfix.

**Comment by jgulick48** [comment]
Fixed in [v1.0.0.76](https://github.com/jgulick48/NiceHashProfitabilityCalculator/releases/tag/1.0.0.76)
