### ISSUE TITLE
ER Implement an avarage value for the different reports

### ISSUE THREAD

**Issue by rgjertsen** [jgulick48/NiceHashProfitabilityCalculator#45]
I have noticed that the earnings, and other values, have some spikes and changes every day.
Would it not be a more acurate number if we had avarage earnings and watts per 12 or 24 hour?

**Comment by jgulick48** [comment]
If you change the time frame to a longer period the averages are over longer times. I’ll have to look at the exact scaling but if you do a week it will scale to show data points every few hours.

**Comment by rgjertsen** [comment]
Yea, but I think it's a little long to wait 12 hours for a new update if I have it on a week.

**Comment by jgulick48** [comment]
Are you looking for an overall average for each card to be displayed for a specific time period?
Rather than adding this to a graph I may just create a report for this that you can easily select in the exports option. Added to the backlog for some more quick reports.

**Comment by jgulick48** [comment]
I have added a report to the Card Exports tab that will show an average per timespan for the selected time period.  Keep in mind though that this is a rather large amount of data it has to process and the timeout is set to 30 seconds right now and if it take too long you will get an error.  Keep your time frame shorter or keep the interval larger to get reports to process.

**Comment by rgjertsen** [comment]
I am trying to get an avarage earnings report per card now, but I am not really sure how to use the "Export" section.
I choose Avarage earnings per card, input my wallet address and select Last week.
Do I hit Refresh, Run report or Save?
I have tried them all, but I am not getting anything in the gray box.
